openapi: 3.1.0
servers:
  - description: auth
    url: http://localhost:3000/
info:
  contact:
    name: Franco
    email: franco1conci@gmail.com
    url: https://www.linkedin.com/in/franco-conci/
  version: 0.0.1
  title: Auth api
  description: |
    ### Introduction
      Endpoints specifications and data structures for Auth server api\
paths:
  /api/clients:
    post:
      tags:
        - Client
      summary: Client registration
      requestBody:
        description: client request
        content:
          application/json:
            schema:
              properties:
                clientType:
                  type: string
                  description: Client type as described by rfc6749
                  enum:
                    - confidential
                    - public
                redirectUrl:
                  type: string
                  description: Redirect url as specified by rfc6749
                scopes:
                  type: array
                  description: List of available scopes
                  minItems: 1
                  maxItems: 100
                  items:
                    type: string
                    description: Application scope
                applicationName:
                  type: string
                  description: Application name
                  minLength: 1
                  maxLength: 256
                ApplicationUrl:
                  type: string
                  description: Application Url
                  minLength: 1
                  maxLength: 256
                description:
                  type: string
                  description: Application description
                  minLength: 1
                  maxLength: 524
                logo:
                  type: string
                  description: Application logo encoded in base64
              required:
                - clientType
                - redirectUrl
                - scopes
              additionalProperties: false
      responses:
        '200':
          description: client response
          content:
            application/json:
              schema:
                properties:
                  id:
                    description: entity id in uuid format
                    type: string
                    pattern: >-
                      ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89AB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
        '400':
          description: malformed request
        '401':
          description: unauthorized
        '409':
          description: conflicted request
        '500':
          description: server error
  /api/code:
    get:
      tags:
        - Codes
      summary: Code exchange
      parameters:
        - in: query
          name: client_id
          description: Client id
          schema:
            properties:
              id:
                description: entity id in uuid format
                type: string
                pattern: >-
                  ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89AB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
          required: true
        - in: query
          name: redirect_uri
          description: Redirect url
          schema:
            properties:
              redirectUrl:
                type: string
                description: Redirect url as specified by rfc6749
          required: true
        - in: query
          name: grant_type
          description: Grant type
          schema:
            properties:
              grantType:
                description: 'Grant type '
                enum:
                  - authorization_code
                  - refresh_token
                  - password
                  - client_credentials
          required: true
        - in: query
          name: code
          description: code
          schema:
            properties:
              code:
                description: Code to exchange for an auth token
                type: string
          required: true
      responses:
        '200':
          description: Token response
          content:
            application/json:
              schema:
                description: Token response
                properties:
                  access_token:
                    description: jwt token returned when authenticating successfully
                    type: string
                  token_type:
                    type: string
                    description: Token type and how to use it
                  scope:
                    type: array
                    description: List of available scopes
                    minItems: 1
                    maxItems: 100
                    items:
                      type: string
                      description: Application scope
                  expires_in:
                    type: string
                    description: Expiration timer in ms
                    pattern: ^([1-9]){1}(([0-9]){0,6})?$
                    minLength: 1
                    maxLength: 256
                  state:
                    type: string
                    description: >-
                      State as sent via the request. Required only if it had
                      been sent by the request
                    minLength: 1
                    maxLength: 256
                required:
                  - token_type
                  - scope
                  - expires_in
                additionalProperties: false
        '500':
          description: server error
  /auth:
    get:
      tags:
        - Auth
      summary: Auth endpoint
      parameters:
        - in: query
          name: response_type
          description: Expected response type
          schema:
            type: string
            enum:
              - code
          required: true
        - in: query
          name: client_id
          description: Client id
          schema:
            properties:
              id:
                description: entity id in uuid format
                type: string
                pattern: >-
                  ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[4][0-9a-fA-F]{3}-[89AB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
          required: true
        - in: query
          name: redirect_uri
          description: Redirect URI
          schema:
            type: string
          required: false
        - in: query
          name: scope
          description: Scope
          schema:
            type: string
          required: false
        - in: query
          name: state
          description: Application-defined state
          schema:
            type: string
          required: false
      responses:
        '302':
          description: Code response
          content:
            application/json:
              schema:
                description: Code response
                headers:
                  Location:
                    description: >-
                      URI the user will be redirected to in order to request the
                      token
                    schema:
                      type: string
                      examples:
                        - >-
                          https://www.example.com/somepath?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
                        - >-
                          https://www.example.com/somepath?error=invalid_request&error_description=description&error_uri=example&state=xzy
        '500':
          description: server error
components:
  schemas:
    client:
      properties:
        clientType:
          type: string
          description: Client type as described by rfc6749
          enum:
            - confidential
            - public
        redirectUrl:
          type: string
          description: Redirect url as specified by rfc6749
        scopes:
          type: array
          description: List of available scopes
          minItems: 1
          maxItems: 100
          items:
            type: string
            description: Application scope
        applicationName:
          type: string
          description: Application name
          minLength: 1
          maxLength: 256
        ApplicationUrl:
          type: string
          description: Application Url
          minLength: 1
          maxLength: 256
        description:
          type: string
          description: Application description
          minLength: 1
          maxLength: 524
        logo:
          type: string
          description: Application logo encoded in base64
      required:
        - clientType
        - redirectUrl
        - scopes
      additionalProperties: false
    code:
      description: Code to exchange for an auth token
      type: string
